"""Transmission-line response analysis utilities for analog signal paths."""

__version__ = "0.1.0"

from .analysis import (
    IfftConfig,
    IfftParameterChoice,
    PhaseAnalysisConfig,
    PhaseGroupDelayResult,
    RiseMetrics,
    TimeDomainResponse,
    analyze_phase_group_delay,
    analyze_rise_from_s21,
    choose_ifft_parameters,
    compensate_linear_phase,
    first_level_crossing,
    fit_linear_phase,
    recover_time_domain_response,
    select_trusted_group_delay_band,
)
from .core import PreparedS21, RawS21Data
from .io import (
    ScopeTrace,
    Touchstone2Port,
    read_mat_s21,
    read_s21,
    read_s2p,
    read_scope_csv,
    read_touchstone_2port,
    subtract_scope_background,
)
from .output.reports import write_phase_group_delay_report, write_rise_report, write_time_domain_csv


def plot_phase_group_delay(*args, **kwargs):
    from .output.plots import plot_phase_group_delay as _plot_phase_group_delay

    return _plot_phase_group_delay(*args, **kwargs)


def plot_rise_analysis(*args, **kwargs):
    from .output.plots import plot_rise_analysis as _plot_rise_analysis

    return _plot_rise_analysis(*args, **kwargs)


def plot_rise_comparison(*args, **kwargs):
    from .output.plots import plot_rise_comparison as _plot_rise_comparison

    return _plot_rise_comparison(*args, **kwargs)
from .signals import (
    ACZWave,
    CosEnv,
    Differential,
    FlattopWave,
    NormalizedStepTrace,
    find_step_edge_index,
    gen_alpha_drag,
    level_crossing_time,
    measure_rise_time,
    normalize_step_trace,
    show_spectrum,
    theta_sl,
)
from .sparams import (
    FIRCorrectionDesign,
    PreprocessConfig,
    RippleCorrectionTarget,
    S21BandwidthWindow,
    SimpleMultiexpFitResult,
    add_dc_anchor,
    build_ripple_correction_target,
    calibrate_s21_by_simple_multiexp,
    check_fft_ready_grid,
    design_fir_sequence_from_s21,
    estimate_delay_from_phase,
    design_interpolated_ripple_correction_fir,
    design_real_fir_from_response,
    filter_by_S21,
    filter_waveform_by_s21,
    find_step_response_care_points,
    fit_s21_with_simple_multiexp,
    fit_simple_multiexp,
    frequency_response,
    group_delay_from_s21,
    impulse_to_step_response,
    interpolate_fir_time_domain,
    oscillatory_multiexp_impulse_response,
    oscillatory_multiexp_s21,
    prefix_sum,
    prepare_s21,
    reponse_simple_multiexp,
    repo_roundtrip_s2p_config,
    s21_simple_multiexp,
    s21_to_impulse_response,
    select_usable_s21_band,
    simple_multiexp_impulse_response,
    simple_multiexp_s21,
    simple_multiexp_step_response,
    standing_wave_s21,
)

__all__ = [
    "__version__",
    "ACZWave",
    "CosEnv",
    "Differential",
    "FlattopWave",
    "FIRCorrectionDesign",
    "IfftConfig",
    "IfftParameterChoice",
    "NormalizedStepTrace",
    "PhaseAnalysisConfig",
    "PhaseGroupDelayResult",
    "PreparedS21",
    "PreprocessConfig",
    "RawS21Data",
    "RippleCorrectionTarget",
    "RiseMetrics",
    "S21BandwidthWindow",
    "ScopeTrace",
    "SimpleMultiexpFitResult",
    "TimeDomainResponse",
    "Touchstone2Port",
    "add_dc_anchor",
    "build_ripple_correction_target",
    "design_fir_sequence_from_s21",
    "analyze_phase_group_delay",
    "analyze_rise_from_s21",
    "calibrate_s21_by_simple_multiexp",
    "check_fft_ready_grid",
    "choose_ifft_parameters",
    "compensate_linear_phase",
    "estimate_delay_from_phase",
    "design_interpolated_ripple_correction_fir",
    "design_real_fir_from_response",
    "filter_by_S21",
    "filter_waveform_by_s21",
    "find_step_edge_index",
    "find_step_response_care_points",
    "first_level_crossing",
    "fit_linear_phase",
    "fit_s21_with_simple_multiexp",
    "fit_simple_multiexp",
    "frequency_response",
    "gen_alpha_drag",
    "group_delay_from_s21",
    "impulse_to_step_response",
    "interpolate_fir_time_domain",
    "level_crossing_time",
    "measure_rise_time",
    "normalize_step_trace",
    "oscillatory_multiexp_impulse_response",
    "oscillatory_multiexp_s21",
    "plot_phase_group_delay",
    "plot_rise_analysis",
    "plot_rise_comparison",
    "prefix_sum",
    "prepare_s21",
    "read_mat_s21",
    "read_s21",
    "read_s2p",
    "read_scope_csv",
    "read_touchstone_2port",
    "recover_time_domain_response",
    "reponse_simple_multiexp",
    "repo_roundtrip_s2p_config",
    "s21_simple_multiexp",
    "s21_to_impulse_response",
    "select_trusted_group_delay_band",
    "select_usable_s21_band",
    "show_spectrum",
    "simple_multiexp_impulse_response",
    "simple_multiexp_s21",
    "simple_multiexp_step_response",
    "standing_wave_s21",
    "subtract_scope_background",
    "theta_sl",
    "write_phase_group_delay_report",
    "write_rise_report",
    "write_time_domain_csv",
]
